print('Felipe: Hola')
print("Cris: Hola Felipe")
print("Feliep: Que tal?")
print("Cris: de punta mare")

print('Felipe: Hola')
print("Cris: Hola Felipe")
print("Feliep: Que tal?")
print("Cris: de punta mare")
print('Felipe: jajajaja')
print ("mola el pilot")
print('Felipe: Hola')